# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfxremote', '0002_chore_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
